apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: netcore-micro
build:
  artifacts:
    - image: pjgeutjens/netcore_platformservice
      context: PlatformService
      docker:
        dockerfile: Dockerfile
    - image: pjgeutjens/netcore_commandservice
      context: CommandsService
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/skaffold/*
